name: Kotlin Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
        
      - name: Check Directory Structure
        run: ls -R

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x Example1/gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: Example1
